name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numba numpy
        git clone https://github.com/rsokl/MyGrad.git
        cd MyGrad
        python setup.py develop
        cd ..
        python setup.py develop
    - name: Run integration test
      run: |
        python tests/integration.py
